###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdGFsaWVzaXMiLCJpZCI6MSwiaWF0IjoxNzA4MDk3MzEwfQ.DUS2VS4XryDUXqNdwXypH082JlNk2umeXuyKwcDWTBo

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 6,
  "year": 1991
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRmaSIsImlkIjoyLCJpYXQiOjE3MDgwOTA4MjZ9.6zZuylmHtl840IWXkdIEo7dVQTw-KIRULFhJR3FtuKw

{
  "title": "A Cup of Jo",
  "author": "Joanna Goddar",
  "url": "https://cupofjo.com/",
  "year": 2020,
  "likes": 6
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRmaSIsImlkIjoyLCJpYXQiOjE3MDgwOTA4MjZ9.6zZuylmHtl840IWXkdIEo7dVQTw-KIRULFhJR3FtuKw

{
  "title": "ADVICE FROM A TWENTY SOMETHING",
  "author": "Amanda Holstein",
  "url": "https://advicefromatwentysomething.com/about/",
  "likes": 2
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdGFsaWVzaXMiLCJpZCI6MSwiaWF0IjoxNzA4MDk3MzEwfQ.DUS2VS4XryDUXqNdwXypH082JlNk2umeXuyKwcDWTBo

{
  "title": "CUPCAKES & CASHMERE",
  "author": "Emily Schuman",
  "url": "https://cupcakesandcashmere.com/",
  "likes": 6
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRmaSIsImlkIjoyLCJpYXQiOjE3MDgwOTA4MjZ9.6zZuylmHtl840IWXkdIEo7dVQTw-KIRULFhJR3FtuKw

{
  "title": "Giang oi",
  "author": "Giang oi",
  "url": "https://giangoi.com/",
  "likes": 25
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRmaSIsImlkIjoyLCJpYXQiOjE3MDgwOTA4MjZ9.6zZuylmHtl840IWXkdIEo7dVQTw-KIRULFhJR3FtuKw

{
  "title": "Nha cua Giang",
  "author": "Giang oi",
  "url": "https://nhacuagiang.com/",
  "likes": 6
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRmaSIsImlkIjoyLCJpYXQiOjE3MDgwOTA4MjZ9.6zZuylmHtl840IWXkdIEo7dVQTw-KIRULFhJR3FtuKw

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "year": 2010,
  "likes": 12
}